### ISSUE TITLE
TODO before contest

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#1712]
- [] https://github.com/google/fuzzbench/issues/1708
- [] https://github.com/google/fuzzbench/issues/1706
- [] https://github.com/google/fuzzbench/issues/1636
- [] https://github.com/google/fuzzbench/issues/1648
- [] honggfuzz broken on https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/22a9614c-3927-464c-af0a-1c864b8f1f3d;step=4?project=fuzzbench
